### ISSUE TITLE
Unnecessary call into base class

### ISSUE THREAD

**Issue by SeanFeldman** [davidrevoledo/ServiceBus.LogginPlugin#1]
https://github.com/davidrevoledo/ServiceBus.LogginPlugin/blob/2bfa813f306ec4d3fccd34c705fd2d4c913676cf/src/ServiceBus.LogginPlugin/LogginPlugin.cs#L78

It's enough to return the `message`.

**Comment by davidrevoledo** [comment]
@SeanFeldman sure ! thanks :)

**Comment by davidrevoledo** [comment]
@SeanFeldman I'm using this code in PRD but this changes will not break anything so I'm changing in other branch to push a 1.0.1 version without breaking changes.

Tasks a lot for your help BTW :) 

https://github.com/davidrevoledo/ServiceBus.LogginPlugin/commit/0aeb428e32289e7982c06fa415bd8977bae02c00

**Comment by SeanFeldman** [comment]
👍
I've sent a few minor observations/comments.
