### ISSUE TITLE
Loggin should be logging.

### ISSUE THREAD

**Issue by Expecho** [davidrevoledo/ServiceBus.LogginPlugin#13]
There is a small typo all over the code base, the correct word should be logging. In this early stage it might be relative easy to fix. 

I wouldn't mind to create a PR to fix this if it aligns with your plans.

**Comment by davidrevoledo** [comment]
@Expecho sure go ahead :) great thanks.

**Comment by davidrevoledo** [comment]
Fixed :)

**Comment by davidrevoledo** [comment]
@Expecho Repo renamed :)
