### ISSUE TITLE
Task.Run over Task.Factory.StartNew

### ISSUE THREAD

**Issue by SeanFeldman** [davidrevoledo/ServiceBus.LogginPlugin#2]
https://github.com/davidrevoledo/ServiceBus.LogginPlugin/blob/2bfa813f306ec4d3fccd34c705fd2d4c913676cf/src/ServiceBus.LogginPlugin/LogginPlugin.cs#L72

`Task.Factory.StartNew` is considered dangerous if not used intentionally.

**Comment by davidrevoledo** [comment]
The idea is run the method in background without blocking the return what other option you would consider to perform the background operation ? @SeanFeldman

**Comment by SeanFeldman** [comment]
`Task.Run` gives you exactly that w/o using less preferred `Task.Factory.StartNew`. More [here](https://blog.stephencleary.com/2013/08/startnew-is-dangerous.html).

**Comment by davidrevoledo** [comment]
@SeanFeldman ohh the great Stephen  the god of the Async thanks didn't read that article.

**Comment by davidrevoledo** [comment]
changed here -> https://github.com/davidrevoledo/ServiceBus.LogginPlugin/commit/01f5ebe0041374fa625fc62412bb635cfbfed5b7

This won't break anything so I can push easily to master and publish 1.0.1 version with other change
