### ISSUE TITLE
ServiceLocator should not be baked into the plugin

### ISSUE THREAD

**Issue by SeanFeldman** [davidrevoledo/ServiceBus.LogginPlugin#3]
https://github.com/davidrevoledo/ServiceBus.LogginPlugin/blob/def057b3647e67d9edd9cbf6d72e750876b363cf/src/ServiceBus.LogginPlugin/LogginPlugin.cs#L88

This is personal opinion, so you're free to disregard it.
Coupling plugin to service locator feels off. Dependencies should be passed into the plugin w/o the need to resolve anything "auto-magically". This makes the seam very simple and lifetime management controllable by users.

**Comment by davidrevoledo** [comment]
@SeanFeldman yeah I know that, the problem is the Service is created internally by ServiceFactory.

If someone wants to implement a Custom Operation I can not create that class on the flight without using the configured Dependency Inyection engine.

`IServiceProvider` is the base interface to resolve dependencies and it's implemented by pretty much all the engines.

One option could be get directly the instance, but this is only needed for `CustomServices` as the Storage and Trace Services are being created internally.

What do you think ?

**Comment by SeanFeldman** [comment]
> `IServiceProvider` is the base interface to resolve dependencies and it's implemented by pretty much all the engines.

It depends what do you mean by "all engines". If this is your code, then this plugin is not for necessarily targeting general public. Personally, I'd rather pass in an instance. In general, if you want to abstract the part of your logger, better to come up with an abstraction for this specific plugin and provide default implementations. That way, anyone who's like to add their own logger implementation would be able to do so. And you don't have to "bake that into" the project.

**Comment by davidrevoledo** [comment]
@SeanFeldman Yeah I make sense, really it's not used yet as I'm only using the Table Storage so it won't break anything .
I wanted to extend the configuration to allow custom usages 

You mean something like this
```

 queueClient = new QueueClient(ServiceBusConnectionString, QueueName);

       queueClient.RegisteredPlugins.Add(new LogginPlugin(configurations =>
       {
            configurations.LogginType = LogginType.Custom;
            configurations.ServiceProvider = _serviceProvider;
            configurations.CustomLogginService = new CustomLogginService()
       }));
```
That way the client has the responsibility to resolve the type, right ?

**Comment by SeanFeldman** [comment]
Yes, just w/o 

> configurations.ServiceProvider = _serviceProvider;

As I'm not clear what that one would need. I'd even go as simple as having several extension methods

```c#
queueClient.RegisterLoggingPlugin(new StorageTableLogger());
queueClient.RegisterLoggingPlugin(new ConsoleLogger());
```
where both `StorageTableLogger` and `ConsoleTableLogger` would implement `ILoggingPluginLogger` (funky name, just an example).

**Comment by davidrevoledo** [comment]
yeah but with that hey need to implement whole pipeline I have the idea that the people just Implement ILoggerService interface and complete the method LogMessageSent and the future events there.

**Comment by SeanFeldman** [comment]
People will either use the plugin or open an issue to add features.
If you will leave a way to do custom implementation, only those that really need it will implement. Vast majority will ask you to add it 😉

**Comment by davidrevoledo** [comment]
@SeanFeldman I'm thinking of keeping like this https://github.com/davidrevoledo/ServiceBus.LogginPlugin/blob/removeServiceLocator/samples/ServiceBusSedingToQueue/Program.cs#L55

And also add the extension to add a LogginPlugin Later but with this I remove the ServiceLocator

**Comment by davidrevoledo** [comment]
https://github.com/davidrevoledo/ServiceBus.LogginPlugin/pull/7
