### ISSUE TITLE
Namespace typo

### ISSUE THREAD

**Issue by SeanFeldman** [davidrevoledo/ServiceBus.LogginPlugin#4]
https://github.com/davidrevoledo/ServiceBus.LogginPlugin/blob/def057b3647e67d9edd9cbf6d72e750876b363cf/src/ServiceBus.LogginPlugin/Infraestructure/MessageExtensions.cs#L30

Most likely because of the containing folder.

**Comment by davidrevoledo** [comment]
Fixed here, great thanks.

https://github.com/davidrevoledo/ServiceBus.LogginPlugin/commit/db713ba40b6647cb1681243d441cb01d5f4043a0
