### ISSUE TITLE
Sequence number of a sent message cannot have value

### ISSUE THREAD

**Issue by SeanFeldman** [davidrevoledo/ServiceBus.LogginPlugin#5]
https://github.com/davidrevoledo/ServiceBus.LogginPlugin/blob/def057b3647e67d9edd9cbf6d72e750876b363cf/src/ServiceBus.LogginPlugin/Infraestructure/MessageExtensions.cs#L56

**Comment by davidrevoledo** [comment]
@SeanFeldman this is a workaround to Serialize the message, I read that this property is server based so will be overwritten. 

Am I wrong ?

**Comment by SeanFeldman** [comment]
If you're logging a message going out, there should be fidelity to what's been sent out.
Since the property **cannot** be set on the client, as a user of the plugin I'd expect to see no value set.
By modifying it, you're making a value up that was not there. A logger should not do that 🙂

**Comment by davidrevoledo** [comment]
Enqueued time of a sent message cannot have a value #6

**Comment by davidrevoledo** [comment]
@SeanFeldman I figure it out that if you set the properties but with no value, Serialization is well done but no fake values :) https://github.com/davidrevoledo/ServiceBus.LogginPlugin/commit/d91a515c12daa2eda93f74145fd721ec313d0bf9
