### ISSUE TITLE
Enqueued time of a sent message cannot have a value

### ISSUE THREAD

**Issue by SeanFeldman** [davidrevoledo/ServiceBus.LogginPlugin#6]
https://github.com/davidrevoledo/ServiceBus.LogginPlugin/blob/def057b3647e67d9edd9cbf6d72e750876b363cf/src/ServiceBus.LogginPlugin/Infraestructure/MessageExtensions.cs#L53

**Comment by davidrevoledo** [comment]
will be removed here https://github.com/davidrevoledo/ServiceBus.LogginPlugin/issues/5
