### ISSUE TITLE
Should readme.md be updated to reflect the latest code changes?

### ISSUE THREAD

**Issue by SeanFeldman** [davidrevoledo/ServiceBus.LogginPlugin#9]

**Comment by davidrevoledo** [comment]
@SeanFeldman  It is I think.  Custom service in readme is:

```C# 
queueClient.RegisterLogginService(new CustomLogginService());
```

And the references to the IServiceProvider as a param was removed. 

The other changes : 
- Fire and forget way to log in background is internal as well the fake properties to serialize the message

**Comment by SeanFeldman** [comment]
Ah, my bad.
